# Generated by Django 3.2.5 on 2021-07-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsklad', '0002_auto_20210730_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='mass_True',
            new_name='mass_true',
        ),
    ]
